# :schema node_modules/wrangler/config-schema.json
name = "amarjeet-app-api"
compatibility_date = "2024-10-22"
compatibility_flags = [ "nodejs_compat_v2" ]
main = "src/index.ts"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[env.dev]
workers_dev = true
